### ISSUE TITLE
Not working on Fedora 38

### ISSUE THREAD

**Issue by miguelangelcg25** [wallneradam/tc420#17]
Not working on Fedora 38, when executing `tc420 --help` I get this error:

```
Traceback (most recent call last):
  File "/home/miguelangel/.local/bin/tc420", line 5, in <module>
    from tc420.__main__ import main
  File "/home/miguelangel/.local/lib/python3.12/site-packages/tc420/__main__.py", line 286, in <module>
    @cmd_group.resultcallback()
     ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Group' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?
``` 

I created plugdev group, added my user, re-logged in but did not work.

**Comment by git-madresc** [comment]
Changing 'resultcallback' to 'result_callback' as suggested worked for me.

**Comment by schwabix-1311** [comment]
This is fixed by PR #11.
Unfortunately Adam seems to no longer maintain this code.

To make this and other fixes available I created a fork https://github.com/schwabix-1311/tc420 to add all new stuff there.
My fork includes all PRs found here, namely
- update to package click >= 8.1.0  => rename of resultcallback to result_callback
- non-sudo use of tc420
- USBTimeoutErrors
- multiple TC420 controllers connected to same system
